version: "2"
services:
  elasticsearch:
    image: elasticsearch:6.8.0
    environment:
      - http.host=0.0.0.0
      - thread_pool.index.queue_size=100000
      - thread_pool.search.queue_size=100000
      - thread_pool.bulk.queue_size=100000
  cortex:
    image: thehiveproject/cortex:3.0.0-RC4
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:9001:9001"
